### ISSUE TITLE
sha256_password could not be loaded

### ISSUE THREAD

**Issue by Yanson** [Angatar/mysql-s3-backup#1]
I receive the following error when connecting to a MySQL 8 server, which uses `caching_sha2_password` by default:

> mysqldump: Got error: 1045: "Plugin sha256_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/sha256_password.so: No such file or directory" when trying to connect

Running `apk add --no-cache mariadb-connector-c` at the beginning of my backup script solves this, but I think it would be better if it's part of the image.

**Comment by Angatar** [comment]
Thank you for your feedback and for opening this issue along with your solution. Indeed, in MySQL 8, caching_sha2_password is now the default authentication plugin rather than the deprecated mysql_native_password. 

I've added the mariadb-connector-c client library to the image, which fixes this connection issue as you suggested.

Thanks again for your input! It helps us a lot in maintaining functional Docker images for the community.
